### ISSUE TITLE
Clicking on the link to the Google Group does provide a mechanism to subscribe

### ISSUE THREAD

**Issue by mpfl** [rse-aunz/rse-au#66]
Viewing `README.md`, clicking on this link:

> https://groups.google.com/forum/?#!forum/rse-nz-au

Gives you an error message:

> You do not have permission to access this content.

There is no obvious way to subscribe.

**Comment by rowlandm** [comment]
Thanks Matthias. Not sure why that is.... Will try and have a look this
weekend :(

Regards,


Rowland

_______________



*Rowland Mosbergen *

Petascale Campus Initiative - Facilitator

The University of Melbourne, Victoria 3010 Australia

*E:  *rowland.mosbergen@unimelb.edu.au
*M: *+61 3 834 46623

I acknowledge the Wurundjeri people of the Kulin nation as the custodians
of the land on which I work, live, and raise my family. I pay my respects
to their elders past, present and future.

**Comment by rowlandm** [comment]
https://support.google.com/a/thread/5541512?hl=en

**Comment by rowlandm** [comment]
https://support.google.com/a/thread/6143498?hl=en

**Comment by gbpoole** [comment]
I get the same error when I try: https://groups.google.com/forum/#!forum/rse-nz-au/join

Any chance you've had a chance to check this out yet?  I've been trying (and failing) to join for the better part of a week now.

**Comment by manodeep** [comment]
@gbpoole I tried out the solutions outlined above via a different browser and nothing seemed to work. Remains an outstanding issue, at least for now. 

@rowlandm Did those solutions work for you?

**Comment by rowlandm** [comment]
Nope. Plus I didn't have admin access.

**Comment by manodeep** [comment]
Hmm - okay. I changed the group directory setting to "Visible to anyone on the web". Hopefully, that will do the trick. (I could submit the request to join the group but I don't see the join request on the group admin interface. Might have to alter some more group permissions)

**Comment by manodeep** [comment]
This should be resolved now. @gbpoole could request to join the group with this new setting. 

@mpfl Will you please check if you can sign-up now? If so, we can close this issue.

**Comment by rowlandm** [comment]
This seems to be working. Will close now. If anything is still wrong, please reopen.

**Comment by adamzammit** [comment]
Not sure if it just me but I can't join with a similar error as in this issue

**Comment by manodeep** [comment]
@adamzammit Quite a few members have joined recently - so there must be something specific that is preventing you from signing up. If you are okay to share your email address here, then I can invite you to join the group.

**Comment by adamzammit** [comment]
Thanks @manodeep - glad to: adam.zammit@acspri.org.au

**Comment by manodeep** [comment]
Invitation sent
